spring.datasource.url=jdbc:postgresql://c4grve4a94cme9.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d9ahu0k324cim1
spring.datasource.username=u73mb1bk4q9pqn
spring.datasource.password=p099fdb47b347d3a682b2963b7b74aaee1014fea51bc969f176b2e117019972b4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false